# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f004hf2/workspace/module6/module6.srcs/sources_1/bd/module6_hw/ip/module6_hw_processing_system7_0_0/module6_hw_processing_system7_0_0.xci
# IP: The module: 'module6_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f004hf2/workspace/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_processing_system7_0_0/module6_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /thayerfs/home/f004hf2/workspace/module6/module6.srcs/sources_1/bd/module6_hw/ip/module6_hw_processing_system7_0_0/module6_hw_processing_system7_0_0.xci
# IP: The module: 'module6_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f004hf2/workspace/module6/module6.gen/sources_1/bd/module6_hw/ip/module6_hw_processing_system7_0_0/module6_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module6_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
